// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerSystem.UserService.Data;

#nullable disable

namespace PartnerSystem.UserService.Data.Persistence.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerSystem.UserService.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("PartnerExternalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ExternalId = 1L,
                            Name = "Alice"
                        },
                        new
                        {
                            Id = 2L,
                            ExternalId = 2L,
                            Name = "Bob",
                            PartnerExternalId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            ExternalId = 3L,
                            Name = "Charlie",
                            PartnerExternalId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            ExternalId = 4L,
                            Name = "Dave",
                            PartnerExternalId = 3L
                        },
                        new
                        {
                            Id = 5L,
                            ExternalId = 5L,
                            Name = "Eve",
                            PartnerExternalId = 4L
                        },
                        new
                        {
                            Id = 6L,
                            ExternalId = 6L,
                            Name = "Frank"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
