// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PartnerSystem.CommissionService.Data;

#nullable disable

namespace PartnerSystem.CommissionService.Data.Persistence.Migrations
{
    [DbContext(typeof(CommissionDbContext))]
    [Migration("20261001114559_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PartnerSystem.CommissionService.Data.Entities.CommissionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AccruedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("BeneficiaryUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SchemaType")
                        .HasColumnType("integer");

                    b.Property<long>("SourceUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "BeneficiaryUserId")
                        .IsUnique();

                    b.ToTable("Commissions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccruedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Amount = 10m,
                            BeneficiaryUserId = 4L,
                            EventId = 1L,
                            Level = 1,
                            SchemaType = 0,
                            SourceUserId = 5L,
                            Status = 0
                        },
                        new
                        {
                            Id = 2L,
                            AccruedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Amount = 20m,
                            BeneficiaryUserId = 3L,
                            EventId = 1L,
                            Level = 2,
                            SchemaType = 0,
                            SourceUserId = 5L,
                            Status = 0
                        },
                        new
                        {
                            Id = 3L,
                            AccruedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Amount = 30m,
                            BeneficiaryUserId = 2L,
                            EventId = 1L,
                            Level = 3,
                            SchemaType = 0,
                            SourceUserId = 5L,
                            Status = 0
                        },
                        new
                        {
                            Id = 4L,
                            AccruedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Amount = 40m,
                            BeneficiaryUserId = 1L,
                            EventId = 1L,
                            Level = 4,
                            SchemaType = 0,
                            SourceUserId = 5L,
                            Status = 0
                        });
                });

            modelBuilder.Entity("PartnerSystem.CommissionService.Data.Entities.CommissionSchemaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Schemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Schema = "Linear",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
